OutfitsSet = {}
OutfitsSet.Debug = true
OutfitsSet.UsingOutfitsMenuCmd = true
OutfitsSet.OutfitsMenuCmd = 'outfits'
OutfitsSet.UsingSetOutfitsMenuCmd = true
OutfitsSet.SetOutfitsMenuCmd = 'setoutfit'
OutfitsSet.SetLanguage = 'Ro'

OutfitsSet.Language = {
    Outfits = {
        ['Ro'] = {
            [1] = 'Haine Poliție #1', -- male
            [2] = 'Haine Poliție #2', -- male
            [3] = 'Haine Poliție #3', -- male
            [4] = 'Haine Poliție #4', -- male
            [5] = 'Haine Poliție #5', -- male
            [6] = 'Haine Poliție #6', -- male
            [7] = 'Haine Poliție #7', -- male
            [8] = 'Haine Poliție #8', -- male
            [9] = 'Haine Poliție #9', -- male
            [10] = 'Haine Poliție #10', -- male
            [11] = 'Haine Poliție #11', -- male
            [12] = 'Haine Sisika', -- male
            [13] = 'Haine Poliție #1', -- female
            [14] = 'Haine Poliție #2', -- female
            [15] = 'Haine Poliție #3', -- female
            [16] = 'Haine Poliție #4', -- female
            [17] = 'Haine Poliție #5', -- female
            [18] = 'Haine Sisika', -- female
            [19] = 'Haine Doctor #1', -- male
            [20] = 'Haine Doctor #2', -- male
            [21] = 'Haine Doctor #3', -- male
            [22] = 'Haine Doctor #4', -- male
            [23] = 'Haine Miner #1', -- male
            [24] = 'Haine Miner #2', -- male
            [25] = 'Haine Doctor #1', -- female
            [26] = 'Haine Doctor #2', -- female 
        },
        
        ['En'] = {
            [1] = 'Police Outfit #1', -- male
            [2] = 'Police Outfit #2', -- male
            [3] = 'Police Outfit #3', -- male
            [4] = 'Police Outfit #4', -- male
            [5] = 'Police Outfit #5', -- male
            [6] = 'Police Outfit #6', -- male
            [7] = 'Police Outfit #7', -- male
            [8] = 'Police Outfit #8', -- male
            [9] = 'Police Outfit #9', -- male
            [10] = 'Police Outfit #10', -- male
            [11] = 'Police Outfit #11', -- male
            [12] = 'Sisika Outfit', -- male
            [13] = 'Police Outfit #1', -- female
            [14] = 'Police Outfit #2', -- female
            [15] = 'Police Outfit #3', -- female
            [16] = 'Police Outfit #4', -- female
            [17] = 'Police Outfit #5', -- female
            [18] = 'Sisika Outfit', -- female
            [19] = 'Doctor Outfit #1', -- male
            [20] = 'Doctor Outfit #2', -- male
            [21] = 'Doctor Outfit #3', -- male
            [22] = 'Doctor Outfit #4', -- male
            [23] = 'Miner Outfit #1', -- male
            [24] = 'Miner Outfit #2', -- male
            [25] = 'Doctor Outfit #1', -- female
            [26] = 'Doctor Outfit #2', -- female
        },
        
        ['Fr'] = {
            [1] = 'Tenue Police #1', -- male
            [2] = 'Tenue Police #2', -- male
            [3] = 'Tenue Police #3', -- male
            [4] = 'Tenue Police #4', -- male
            [5] = 'Tenue Police #5', -- male
            [6] = 'Tenue Police #6', -- male
            [7] = 'Tenue Police #7', -- male
            [8] = 'Tenue Police #8', -- male
            [9] = 'Tenue Police #9', -- male
            [10] = 'Tenue Police #10', -- male
            [11] = 'Tenue Police #11', -- male
            [12] = 'Tenue Sisika', -- male
            [13] = 'Tenue Police #1', -- female
            [14] = 'Tenue Police #2', -- female
            [15] = 'Tenue Police #3', -- female
            [16] = 'Tenue Police #4', -- female
            [17] = 'Tenue Police #5', -- female
            [18] = 'Tenue Sisika', -- female
            [19] = 'Tenue Docteur #1', -- male
            [20] = 'Tenue Docteur #2', -- male
            [21] = 'Tenue Docteur #3', -- male
            [22] = 'Tenue Docteur #4', -- male
            [23] = 'Tenue Mineur #1', -- male
            [24] = 'Tenue Mineur #2', -- male
            [25] = 'Tenue Docteur #1', -- female
            [26] = 'Tenue Docteur #2', -- female
        },
        
        ['De'] = {
            [1] = 'Polizei Outfit #1', -- male
            [2] = 'Polizei Outfit #2', -- male
            [3] = 'Polizei Outfit #3', -- male
            [4] = 'Polizei Outfit #4', -- male
            [5] = 'Polizei Outfit #5', -- male
            [6] = 'Polizei Outfit #6', -- male
            [7] = 'Polizei Outfit #7', -- male
            [8] = 'Polizei Outfit #8', -- male
            [9] = 'Polizei Outfit #9', -- male
            [10] = 'Polizei Outfit #10', -- male
            [11] = 'Polizei Outfit #11', -- male
            [12] = 'Sisika Outfit', -- male
            [13] = 'Polizei Outfit #1', -- female
            [14] = 'Polizei Outfit #2', -- female
            [15] = 'Polizei Outfit #3', -- female
            [16] = 'Polizei Outfit #4', -- female
            [17] = 'Polizei Outfit #5', -- female
            [18] = 'Sisika Outfit', -- female
            [19] = 'Arzt Outfit #1', -- male
            [20] = 'Arzt Outfit #2', -- male
            [21] = 'Arzt Outfit #3', -- male
            [22] = 'Arzt Outfit #4', -- male
            [23] = 'Bergmann Outfit #1', -- male
            [24] = 'Bergmann Outfit #2', -- male
            [25] = 'Arzt Outfit #1', -- female
            [26] = 'Arzt Outfit #2', -- female
        },
        
        ['It'] = {
            [1] = 'Divisa Polizia #1', -- male
            [2] = 'Divisa Polizia #2', -- male
            [3] = 'Divisa Polizia #3', -- male
            [4] = 'Divisa Polizia #4', -- male
            [5] = 'Divisa Polizia #5', -- male
            [6] = 'Divisa Polizia #6', -- male
            [7] = 'Divisa Polizia #7', -- male
            [8] = 'Divisa Polizia #8', -- male
            [9] = 'Divisa Polizia #9', -- male
            [10] = 'Divisa Polizia #10', -- male
            [11] = 'Divisa Polizia #11', -- male
            [12] = 'Divisa Sisika', -- male
            [13] = 'Divisa Polizia #1', -- female
            [14] = 'Divisa Polizia #2', -- female
            [15] = 'Divisa Polizia #3', -- female
            [16] = 'Divisa Polizia #4', -- female
            [17] = 'Divisa Polizia #5', -- female
            [18] = 'Divisa Sisika', -- female
            [19] = 'Divisa Dottore #1', -- male
            [20] = 'Divisa Dottore #2', -- male
            [21] = 'Divisa Dottore #3', -- male
            [22] = 'Divisa Dottore #4', -- male
            [23] = 'Divisa Minatore #1', -- male
            [24] = 'Divisa Minatore #2', -- male
            [25] = 'Divisa Dottore #1', -- female
            [26] = 'Divisa Dottore #2', -- female
        },
        
        ['Br'] = {
            [1] = 'Traje Polícia #1', -- male
            [2] = 'Traje Polícia #2', -- male
            [3] = 'Traje Polícia #3', -- male
            [4] = 'Traje Polícia #4', -- male
            [5] = 'Traje Polícia #5', -- male
            [6] = 'Traje Polícia #6', -- male
            [7] = 'Traje Polícia #7', -- male
            [8] = 'Traje Polícia #8', -- male
            [9] = 'Traje Polícia #9', -- male
            [10] = 'Traje Polícia #10', -- male
            [11] = 'Traje Polícia #11', -- male
            [12] = 'Traje Sisika', -- male
            [13] = 'Traje Polícia #1', -- female
            [14] = 'Traje Polícia #2', -- female
            [15] = 'Traje Polícia #3', -- female
            [16] = 'Traje Polícia #4', -- female
            [17] = 'Traje Polícia #5', -- female
            [18] = 'Traje Sisika', -- female
            [19] = 'Traje Doutor #1', -- male
            [20] = 'Traje Doutor #2', -- male
            [21] = 'Traje Doutor #3', -- male
            [22] = 'Traje Doutor #4', -- male
            [23] = 'Traje Mineiro #1', -- male
            [24] = 'Traje Mineiro #2', -- male
            [25] = 'Traje Doutor #1', -- female
            [26] = 'Traje Doutor #2', -- female
        },
        
        ['Id'] = {
            [1] = 'Seragam Polisi #1', -- male
            [2] = 'Seragam Polisi #2', -- male
            [3] = 'Seragam Polisi #3', -- male
            [4] = 'Seragam Polisi #4', -- male
            [5] = 'Seragam Polisi #5', -- male
            [6] = 'Seragam Polisi #6', -- male
            [7] = 'Seragam Polisi #7', -- male
            [8] = 'Seragam Polisi #8', -- male
            [9] = 'Seragam Polisi #9', -- male
            [10] = 'Seragam Polisi #10', -- male
            [11] = 'Seragam Polisi #11', -- male
            [12] = 'Seragam Sisika', -- male
            [13] = 'Seragam Polisi #1', -- female
            [14] = 'Seragam Polisi #2', -- female
            [15] = 'Seragam Polisi #3', -- female
            [16] = 'Seragam Polisi #4', -- female
            [17] = 'Seragam Polisi #5', -- female
            [18] = 'Seragam Sisika', -- female
            [19] = 'Seragam Dokter #1', -- male
            [20] = 'Seragam Dokter #2', -- male
            [21] = 'Seragam Dokter #3', -- male
            [22] = 'Seragam Dokter #4', -- male
            [23] = 'Seragam Penambang #1', -- male
            [24] = 'Seragam Penambang #2', -- male
            [25] = 'Seragam Dokter #1', -- female
            [26] = 'Seragam Dokter #2', -- female
        },
    },
    Menu = {
        ['Ro'] = {
            ['police'] = 'HAINE POLIȚIE',
            ['prison'] = 'HAINE ÎNCHISOARE',
            ['doctor'] = 'HAINE MEDICI',
            ['miner'] = 'HAINE MINER',
        },
        ['En'] = {
            ['police'] = 'POLICE OUTFITS',
            ['prison'] = 'PRISON OUTFITS',
            ['doctor'] = 'DOCTOR OUTFITS',
            ['miner'] = 'MINER OUTFITS',
        },
        ['Fr'] = {
            ['police'] = 'TENUES POLICE',
            ['prison'] = 'TENUES PRISON',
            ['doctor'] = 'TENUES DOCTEUR',
            ['miner'] = 'TENUES MINER',
        },
        ['De'] = {
            ['police'] = 'POLIZEI KLEIDUNG',
            ['prison'] = 'GEFÄNGNIS KLEIDUNG',
            ['doctor'] = 'DOKTOR KLEIDUNG',
            ['miner'] = 'MINER KLEIDUNG',
        },
        ['It'] = {
            ['police'] = 'DIVISE POLIZIA',
            ['prison'] = 'DIVISE PRIGIONE',
            ['doctor'] = 'DIVISE DOCTEUR',
            ['miner'] = 'DIVISE MINER',
        },
        ['Br'] = {
            ['police'] = 'ROUPAS DE POLÍCIA',
            ['prison'] = 'ROUPAS DE PRISÃO',
            ['doctor'] = 'ROUPAS DE DOUTOR',
            ['miner'] = 'ROUPAS DE MINER',
        },
        ['Id'] = {
            ['police'] = 'SERAGAM POLISI',
            ['prison'] = 'SERAGAM PENJARA',
            ['doctor'] = 'SERAGAM DOKTER',
            ['miner'] = 'SERAGAM MINER',
        },
    }, 
}